spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  data:
    rest:
      base-path: /data-api
  jms:
    template:
      default-destination: tacocloud.order.queue

taco:
  orders:
    pageSize: 10

logging:
  level:
    tacos: DEBUG


